name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:        
          push: true
          tags: ${{secrets.DOCKER_REPO}}:latest
          labels: ${{secrets.DOCKER_REPO}}
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    -
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{secrets.GCP_CREDENTIALS}}'
    - 
      name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - 
      name: 'Deploy with gcloud CLI'
      run: 'gcloud run deploy ${{secrets.GCP_REPO_NAME}} --image=${{secrets.DOCKER_REPO}}:latest --project=${{secrets.GCP_PROJECT}} --port=${{secrets.PORT}} --set-env-vars="CHATBOT_TOKEN=${{secrets.CHATBOT_TOKEN}}, CHATBOT_DISCORD_GUILD=${{secrets.CHATBOT_DISCORD_GUILD}}, SCAN_CHANNEL=${{secrets.SCAN_CHANNEL}}, MODE=${{secrets.MODE}}" --region=${{secrets.GCP_REGION}} --platform=managed'
#   - 
#      id: deploy
#      uses: google-github-actions/deploy-cloudrun@v1
#      with:
#        image: ${{secrets.DOCKER_REPO}}:latest
#        project: ${{secrets.GCP_PROJECT}}
#        service: ${{secrets.GCP_REPO_NAME}}
#        credentials: ${{secrets.GCP_CREDENTIALS}}
#        region: ${{secrets.GCP_REGION}}
#        env_vars: |
#          CHATBOT_TOKEN=${{secrets.CHATBOT_TOKEN}}
#          CHATBOT_DISCORD_GUILD=${{secrets.CHATBOT_DISCORD_GUILD}}
#          SCAN_CHANNEL=${{secrets.SCAN_CHANNEL}}
#         MODE=${{secrets.MODE}}
